[package]
name = "keyrx_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rkyv = { workspace = true }
boomphf = { workspace = true }
fixedbitset = { workspace = true }
arrayvec = { workspace = true }
serde = { workspace = true }
bitvec = { workspace = true }
hashbrown = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "core_bench"
harness = false
